version: '3'

services:
    selenium-hub:
        container_name: selenium-hub
        image: selenium/hub:latest
        ports:
            - "4444:4444"

    selenium-node-firefox:
        container_name: selenium-node-firefox
        restart: unless-stopped
        image: selenium/node-firefox:latest
        environment:
            HUB_PORT_4444_TCP_ADDR: selenium-hub
            HUB_PORT_4444_TCP_PORT: 4444
        depends_on:
            - selenium-hub

    selenium-node-chrome:
        container_name: selenium-node-chrome
        restart: unless-stopped
        image: selenium/node-chrome:latest
        volumes:
            - /dev/shm:/dev/shm
        environment:
            HUB_PORT_4444_TCP_ADDR: selenium-hub
            HUB_PORT_4444_TCP_PORT: 4444
        depends_on:
            - selenium-hub
